import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "@/components/pages/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`antialiased`}
      >
        <NavBarComponent />
        {children}
      </body>
    </html>
  );
}
